services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    ports:
      - "8080:80"
    restart: always

  filebeat:
    image: elastic/filebeat:8.17.0
    container_name: filebeat
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./nginx/logs:/var/log/nginx:ro
    command: ["filebeat", "-e", "--strict.perms=false"]
    depends_on:
      - nginx
    restart: always
