version: '3.8'

services:
  flask-app:
    build: ./python-application
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
    restart: always

