apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      id: python_application
      enabled: true
      paths:
        - /var/log/flask-app/app.log
    setup.template.settings:
      index.number_of_shards: 1
    output.logstash:
      hosts: ["167.235.235.86:5044"]
    processors:
      - add_host_metadata:
          when.not.contains.tags: forwarded
      - add_cloud_metadata: ~
      - add_docker_metadata: ~
      - add_kubernetes_metadata: ~
    
