apiVersion: v1
kind: Service
metadata:
  name: flask-app-nodeport
spec:
  selector:
    app: flask-app
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080
  type: NodePort
