---
- name: Create /mnt/elasticsearch directory
  file:
    path: /mnt/elasticsearch
    state: directory
    mode: '0755'

- name: Copy docker-compose.yml to /mnt/elasticsearch
  copy:
    src: files/docker-compose.yml
    dest: /mnt/elasticsearch/docker-compose.yml
    mode: '0644'

- name: Copy .env to /mnt/elasticsearch
  copy:
    src: files/.env
    dest: /mnt/elasticsearch/.env
    mode: '0644'

- name: Get total system memory in bytes
  ansible.builtin.shell: free -b | awk '/Mem:/ {print $2}'
  register: system_memory
  changed_when: false

- name: Calculate memory limits for Elasticsearch and Kibana
  set_fact:
    es_mem_limit: "{{ (system_memory.stdout | int) }}"
    kb_mem_limit: "{{ (system_memory.stdout | int) // 2 }}"

- name: Update ES_MEM_LIMIT and KB_MEM_LIMIT in .env file
  lineinfile:
    path: /mnt/elasticsearch/.env
    regexp: '^ES_MEM_LIMIT='
    line: "ES_MEM_LIMIT={{ es_mem_limit }}"

- name: Update KB_MEM_LIMIT in .env file
  lineinfile:
    path: /mnt/elasticsearch/.env
    regexp: '^KB_MEM_LIMIT='
    line: "KB_MEM_LIMIT={{ kb_mem_limit }}"